#!/bin/bash

# --------------- config start -----------------------
if [ -n "$BASH" ]; then
  clash_path=$(cd `dirname ${BASH_SOURCE[0]}`;pwd)
else
  clash_path=$(cd `dirname ${(%):-%x}`;pwd)
fi

# clash config path
config=$clash_path"/config"

proxy_endpoint="127.0.0.1:7890"

update_temp_file=$clash_path"/clash_new_config.yaml"

nohup_out=$clash_path"/clash.log"

controller_url="localhost:9090"
# --------------- config end -------------------------

icon_error="🤣👉"
icon_success="😎👍"


validate_config() {
  if [[ -z $clash_path ]]
  then
    echo "[ERROR] $icon_error clash_path config not set."
    return 1
  fi

  if [[ -z $config ]]
  then
    echo "[ERROR] $icon_error config file path config not set."
    return 1
  fi

  if [[ -z $proxy_endpoint ]]
  then
    echo "[ERROR] $icon_error proxy endpoint config not set."
    return 1
  fi

  if [[ -z $update_temp_file ]]
  then
    echo "[ERROR] $icon_error update_temp_file config not set."
    return 1
  fi

  if [[ -z $controller_url ]]
  then
    echo "[ERROR] $icon_error external controller url config not set."
    return 1
  fi

  return 0
}


find_clash() {
  clash=$(find $clash_path -name "clash-*")
  if [[ -z $clash ]]
  then
    echo "[ERROR] $icon_error no clash executable found."
    echo "[ERROR] $icon_error executable name be like: clash-[os]-[arch]-[version]"
    return 1
  fi
  return 0
}


show_usage() {
  echo "Usage:"
  echo ". ${BASH_SOURCE} <option> [param]..."
  echo "Options:"
  echo "start                         start clash"
  echo "stop                          stop clash"
  echo "reload                        reload clash"
  echo "update <url>                  download config from <url> and reload clash"
  echo "proxies                       show proxy information"
  echo "switch <proxy> [selector]     switch proxy to <proxy> in [selector], default selector is Proxies"
  echo "help                          show usage"
}


start() {
  echo "[INFO] stopping potential clash running behind"
  rmLog
  stop
  echo "[INFO] starting http(s) proxy at $proxy_endpoint"
  export http_proxy=$proxy_endpoint
  export https_proxy=$proxy_endpoint

  echo "[INFO] using clash $clash"
  nohup $clash -d $config > $nohup_out 2>&1 &

  sleep 2
  curl -s --connect-timeout 2 google.com > /dev/null
  if [[ $? != 0 ]]
  then
    echo "[ERROR] $icon_error failed to start clash."
    stop
  else
    echo -e "[INFO] $icon_success clash started."
  fi
}


stop() {
  pkill -2 clash
  echo "[INFO] stopped clash."

  unset http_proxy
  unset https_proxy
  echo "[INFO] stopped http(s) proxy."
}


rmLog() {
  echo "[INFO] remove log file."
  rm $nohup_out
}


reload() {
  rmLog
  stop
  sleep 2
  start
}


update() {
  echo "[INFO] backing up the old config file."
  cp $config/config.yaml $config/config.yaml.backup

  echo "[INFO] fetching configuration from \""$1"\""
  wget -L -O $update_temp_file $1
  if [[ $? != 0 ]]
  then
    echo "[ERROR] $icon_error failed to fetch configuration file."
    return
  fi
  mv $update_temp_file $config/config.yaml

  reload
}


show_proxies() {
  curl $controller_url/proxies/$1
}


switch_proxy() {
  curl -X PUT --data "{\"name\": \"$2\"}" $controller_url/proxies/$1
  echo "[INFO] $icon_success switched proxy to \"$2\" in \"$1\"."
}


main() {
  validate_config
  if [[ $? == 1 ]]
  then
    return
  fi

  find_clash
  if [[ $? == 1 ]]
  then
    return
  fi

  if [[ $# == 0 ]]
  then
    show_usage
  fi

  if [[ $1 == "start" ]]
  then
    echo "[INFO] starting..."
    start

  elif [[ $1 == "stop" ]]
  then
    echo "[INFO] stopping..."
    stop

  elif [[ $1 == "reload" ]]
  then
    echo "[INFO] reloading..."
    reload

  elif [[ $1 == "update" ]]
  then
    echo "[INFO] updating..."
    if [[ $# -lt 2 ]]
    then
      echo "[ERROR] required <url> is missing."
      return
    fi
    update $2

  elif [[ $1 == "proxies" ]]
  then
    if [[ $# -lt 2 ]]
    then
      show_proxies Proxies
    else
      show_proxies $2
    fi

  elif [[ $1 == "switch" ]]
  then
    if [[ $# -lt 2 ]]
    then
      show_usage
      return
    fi

    if [[ $# -lt 3 ]]
    then
      switch_proxy Proxies $2
    else
      show_proxies $2 $3
    fi

  else
    show_usage
  fi
}


main $*
